# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.github/" # Location of package manifests
    target-branch: "main"
    labels:
      - "Workflow deps"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"

  - package-ecosystem: "nuget"
    directory: "/src/"
    target-branch: "main"
    labels:
      - "Nuget deps"
    schedule:
      interval: "daily"
      time: "06:00"

