name: Publish nuget package on release

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Build projects
        run: |
          mkdir localNugetPackages
          projects=(
            "Ingress"
            "AlcTableau"
            "Rdf"
            "OwlOntology"
            "RdfOwlTranslator"
            "Parser"
            "Turtle.Parser"
            "Datalog"
            "ELI"
            "Datalog.Parser"
            "OWL2RL2Datalog"
            "Manchester"
            "Manchester.Parser"
            "Api"
            "TestUtils"
            )
          for project in "${projects[@]}"; do
           echo "Building and packing project: $project"
           dotnet build --configuration Release /p:Version=${{ github.event.release.tag_name }} ./src/$project/$project.*sproj
           dotnet pack --configuration Release /p:Version=${{ github.event.release.tag_name }} --output localNugetPackages ./src/$project/$project.*sproj
          done
      
      - name: Build and run test projects
        run: |
          for project in test/*; do
              echo "Building test project: $project"
              dotnet build --configuration Release /p:Version=${{ github.event.release.tag_name }} $project
              dotnet test --configuration Release $project
          done

      - name: Run tests
        run: |
          dotnet test ./DagSemTools.sln 
      
      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          for package in localNugetPackages/*.nupkg; do
            dotnet nuget push "$package" --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
          done
