name: Validate Pull Request
permissions:
  contents: read
  pull-requests: read
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    uses: ./.github/workflows/shared_build_workflow.yml
    with:
      version: 0.0.1-pr-${{ github.event.pull_request.number }}-${{ github.sha }}
