name: Test code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Format code
      run: dotnet format ./DagSemTools.sln --verbosity diagnostic --verify-no-changes --no-restore

    - name: Build First round
      run: | 
        mkdir localNugetPackages
        dotnet build --configuration Release --output localNugetPackages  ./src/Rdf/Rdf.fsproj  
        dotnet build --configuration Release --output localNugetPackages  ./src/AlcTableau/AlcTableau.fsproj
        dotnet build --configuration Release --output localNugetPackages  ./src/Parser/Parser.csproj
        dotnet build --configuration Release --output localNugetPackages  ./src/Turtle.Parser/Turtle.Parser.csproj
        dotnet build --configuration Release --output localNugetPackages  ./src/Datalog/Datalog.fsproj
        dotnet build --configuration Release --output localNugetPackages  ./src/Datalog.Parser/Datalog.Parser.csproj
        dotnet build --configuration Release --output localNugetPackages  ./src/Manchester/Manchester.fsproj
        dotnet build --configuration Release --output localNugetPackages  ./src/Manchester.Parser/Manchester.Parser.csproj
        dotnet build --configuration Release --output localNugetPackages  ./src/Api/Api.csproj

    - name: Run tests
      run: dotnet test ./DagSemTools.sln --no-restore
      
    - name: Run nuget package tests
      run: dotnet test test/NugetTest/NugetTest.sln