name: Test code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Format code
      run: dotnet format ./DagSemTools.sln --verbosity diagnostic --verify-no-changes --no-restore

    - name: Build projects
      run: | 
        mkdir localNugetPackages
        projects=(
          "Rdf"
          "AlcTableau"
          "Parser"
          "Turtle.Parser"
          "Datalog"
          "Datalog.Parser"
          "Manchester"
          "Manchester.Parser"
          "Api"
        )
        for project in "${projects[@]}"; do
            echo "Building and packing project: $project"
            dotnet build  ./src/$project/$project.*sproj
            dotnet pack  --output localNugetPackages ./src/$project/$project.*sproj
        done

    - name: Run tests
      run: dotnet test ./DagSemTools.sln 
      
    - name: Run nuget package tests
      run: dotnet test test/NugetTest/NugetTest.sln